spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    # jsp 파일을 읽어오는것
    static-path-pattern: /static/**
    # static 경로를 읽어오는것
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mshome
    username: root
    password: root
    # DB 연결해주는것 (MY SQL)
mybatis:
  mapper-locations: classpath:mappers/*.xml
server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
